require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '15.1'

inhibit_all_warnings!

prepare_react_native_project!

ENV['RCT_NEW_ARCH_ENABLED'] = '0'
ENV['RCT_USE_PREBUILT_RNCORE'] = '0'
$RNFirebaseAsStaticFramework = true

target 'Famtivity' do
  config = use_native_modules!

  use_frameworks! :linkage => :static

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true,
    :fabric_enabled => false
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.shell_script_build_phases.each do |phase|
        if phase.name == 'Create Symlinks to Header Folders'
          phase.always_out_of_date = '1'
        end
      end
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
  end
end